### ISSUE TITLE
node-fetch instead of got

### ISSUE THREAD

**Issue by coderaiser** [velocityzen/dropbox-stream#14]
Would be great to switch from `got` to `node-fetch` because:

- `got` has [13 dependencies](https://www.npmjs.com/package/got?activeTab=dependencies) and `node-fetch` has [0](https://www.npmjs.com/package/node-fetch?activeTab=dependencies) : installation will be much faster :)
- [official dropbox sdk](https://www.npmjs.com/package/dropbox) uses `fetch` for it is work, so most people should install it anyway
- `fetch` is [standard](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) way of dealing with `http` requests that works in `browser` and `node`.

I can make a pull request with a change, if you find it useful :).

**Comment by velocityzen** [comment]
I don't think it is feasible. 
First of all this lib is made for use in nodejs only due to different File System streams implementations in the browser (FileReader API) and an actual file system. 
Second, if you check the comparison table https://github.com/sindresorhus/got#comparison you'll see how **got** is different. Features like request cancelation, progress events, etc. are essential for real-world app usage.
